name: clean_my_admin
description: A sample web application
dependencies:
  angular: any
  browser: any
  clean_ajax: any
  clean_backend: any
  clean_data: any
  clean_router: any
  clean_sync: any
  crypto: any
  logging: any
  shadow_dom: any
