name: clean_my_admin
description: A sample web application
dependencies:
  browser: any
  clean_ajax: any
  clean_backend: any
  clean_data: ">=0.4.11"
  clean_router: any
  clean_sync: any
  logging: any
  react: any
